"""create food_logs, hydration_logs, weight_check_ins

Revision ID: 7ad6c5014c61
Revises: af82823a980e
Create Date: 2026-05-20 22:38:44.130616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ad6c5014c61'
down_revision: Union[str, None] = 'af82823a980e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.String(), nullable=False),
    sa.Column('grams', sa.Integer(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('kcal_100g', sa.Float(), nullable=False),
    sa.Column('protein_100g', sa.Float(), nullable=False),
    sa.Column('carbs_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('carbs_100g >= 0', name='ck_food_logs_carbs_nonneg'),
    sa.CheckConstraint('fat_100g >= 0', name='ck_food_logs_fat_nonneg'),
    sa.CheckConstraint('grams > 0', name='ck_food_logs_grams_positive'),
    sa.CheckConstraint('kcal_100g >= 0', name='ck_food_logs_kcal_nonneg'),
    sa.CheckConstraint('protein_100g >= 0', name='ck_food_logs_protein_nonneg'),
    sa.ForeignKeyConstraint(['uid'], ['profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_logs_uid_date', 'food_logs', ['uid', 'log_date'], unique=False)
    op.create_table('hydration_logs',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('liters >= 0 AND liters <= 10', name='ck_hydration_liters_range'),
    sa.ForeignKeyConstraint(['uid'], ['profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'log_date')
    )
    op.create_table('weight_check_ins',
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight_kg > 0 AND weight_kg < 500', name='ck_weight_range'),
    sa.ForeignKeyConstraint(['uid'], ['profiles.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid', 'log_date')
    )
    op.create_index('idx_weight_check_ins_uid_date', 'weight_check_ins', ['uid', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weight_check_ins_uid_date', table_name='weight_check_ins')
    op.drop_table('weight_check_ins')
    op.drop_table('hydration_logs')
    op.drop_index('idx_food_logs_uid_date', table_name='food_logs')
    op.drop_table('food_logs')
    # ### end Alembic commands ###
