"""add ingredients to food_logs

Revision ID: 8f3bd6e52f69
Revises: b3c1f2a45d67
Create Date: 2026-06-04 17:31:11.414835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f3bd6e52f69'
down_revision: Union[str, None] = 'b3c1f2a45d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('ingredients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_logs', 'ingredients')
    # ### end Alembic commands ###
